# Site settings
title: Lairworks
email: admin@lairworks.com
description: > # this means to ignore newlines until "baseurl:"
  The new official website for Lairworks.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://lairworks.github.io" # the base hostname & protocol for your site
github_username:  lairworks

# Build settings
markdown: kramdown
highlighter: rouge
